
****************************************************************************
***                       Sentaurus Workbench gjob                       ***
***                          Version O-2018.06                           ***
***                       (1.1029, x86_64, Linux)                        ***
***                                                                      ***
***                Copyright (c) 1994-2018 Synopsys, Inc.                ***
***                                                                      ***
***  This software and the associated documentation are confidential     ***
***  and proprietary to Synopsys, Inc.  Your use or disclosure of this   ***
***  software is subject to the terms and conditions of a written        ***
***  license agreement between you, or your company, and Synopsys, Inc.  ***
****************************************************************************

gjob is running on host 'acs14007.4225.cse.uconn.edu' by user 'student'
Binary '/usr/synopsys/sentaurus/O_2018.06/tcad/current/linux64/bin/../lib/gjob0'
Command line options '-verbose -nice 19 -job 241 -swb_pid 7308 -gsub_pid 23298 -gsub_host acs14007.4225.cse.uconn.edu -gsub_port 35143 /home/student/Documents/ECE4225/Project/IndividualAnalysis/Task1_Copy'
Current directory '/home/student/Documents/ECE4225/Project/IndividualAnalysis/Task1_Copy'
Some relevant environment variables:
	STROOT=/usr/synopsys/sentaurus/O_2018.06
	STRELEASE=current
	STROOT_LIB=/usr/synopsys/sentaurus/O_2018.06/tcad/current/lib
	STDB=/home/student/Documents/ECE4225/Project/IndividualAnalysis
	DATEX=/usr/synopsys/sentaurus/O_2018.06/tcad/current/lib/datexcodes.txt
	DISPLAY=:0

Project '/home/student/Documents/ECE4225/Project/IndividualAnalysis/Task1_Copy'
Loading global tool database '/usr/synopsys/sentaurus/O_2018.06/tcad/current/lib/glib2/tooldb.tcl'
INITIALIZING PREPROCESSOR:
Loading project tree '/home/student/Documents/ECE4225/Project/IndividualAnalysis/Task1_Copy/gtree.dat'
Loading jobs and dependence graph '"/home/student/Documents/ECE4225/Project/IndividualAnalysis/Task1_Copy/gexec.cmd"'
Loading project variables '/home/student/Documents/ECE4225/Project/IndividualAnalysis/Task1_Copy/gvars.dat'
--Get files to preprocess...
--Create file handlers...
--Read the toolflow...
--Analyze tool-file dependencies...
--Read all nodes to preprocess...
--Group nodes into experiments...
--Get all variables...
--Get all parameters...
PREPROCESSOR SUCCESSFULLY INITIALIZED.
PREPROCESSING STEP 1:
Reading file /home/student/Documents/ECE4225/Project/IndividualAnalysis/Task1_Copy/sprocess_fps.cmd
PREPROCESSING STEP 2:
Preprocessing file /home/student/Documents/ECE4225/Project/IndividualAnalysis/Task1_Copy/sprocess_fps.cmd fornode 241
+++Preprocessing results written to /home/student/Documents/ECE4225/Project/IndividualAnalysis/Task1_Copy/pp241_fps.cmd
Start Simulation section
15:35:41 Nov 30 2020     job 241 <sprocess> started on host 'acs14007.4225.cse.uconn.edu': "sprocess -u -b n241_fps.cmd"
15:37:42 Nov 30 2020 +++ job 241 <sprocess> done: exit(0)
End Simulation section
Start Epilogue section
15:37:42 Nov 30 2020 *** job 241 pre/post execution: eval "  gjob::find_extracted_vars "/home/student/Documents/ECE4225/Project/IndividualAnalysis/Task1_Copy" n241_fps.out 241; catch {os_cp "/home/student/Documents/ECE4225/Project/IndividualAnalysis/Task1_Copy/n241_mdr.cmd" "/home/student/Documents/ECE4225/Project/IndividualAnalysis/Task1_Copy/n241_msh.cmd"}; catch {os_cp "/home/student/Documents/ECE4225/Project/IndividualAnalysis/Task1_Copy/n241_mdr.bnd" "/home/student/Documents/ECE4225/Project/IndividualAnalysis/Task1_Copy/n241_msh.bnd"} "
End Epilogue section
Job succeeded
gjob exits with status 0
